
on: 
  workflow_call:
    secrets:
      BOT_TOKEN:
        description: "Service Account Access Token"
        required: true
    inputs:
      REGISTRY:
        required: false
        type: string
        default: ghcr.io
      OWNER:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      BUILD_SECRETS:
        required: false
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Extract Docker metadata
        id: metatata
        uses: docker/metadata-action@v4.4.0
        with:
          images: ${{ inputs.REGISTRY }}/${{ inputs.OWNER }}/${{ inputs.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=long
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
      - name: Log into registry ${{ inputs.REGISTRY }}
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.BOT_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.metatata.outputs.tags }}
          labels: ${{ steps.metatata.outputs.labels }}
          secrets: ${{ inputs.BUILD_SECRETS }}
